services:
  postgresql:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: listed
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      postgresql:
        condition: service_healthy

  seq:
    image: datalust/seq
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_NOAUTHENTICATION: true
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data
      
  listed.api:
    build:
      context: .
      dockerfile: src/Listed.API/Dockerfiles/Dockerfile_local
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      postgresql:
        condition: service_healthy
      seq:
        condition: service_started
    volumes:
      - ./src/Listed.API:/app/Listed.API
      - ./src/Listed.Domain:/app/Listed.Domain
      - ./src/Listed.Application:/app/Listed.Application
      - ./src/Listed.Infrastructure:/app/Listed.Infrastructure
      - /app/Listed.API/bin
      - /app/Listed.API/obj
      
volumes:
  postgresql_data:
    driver: local
  seq_data:
    driver: local
