<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\Listed.Domain\Listed.Domain.csproj" />
	</ItemGroup>
</Project>
